version: 2
updates:
  - package-ecosystem: gradle
    directory: "/app"
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: "/list"
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: "/utilities"
    schedule:
      interval: daily