/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("playground.kotlin-application-conventions")
}

dependencies {
    implementation("com.sksamuel.hoplite:hoplite-core:${Playground_kotlin_application_conventions_gradle.Version.hoplite}")
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("playground.app.AppKt")
}