/*
 * This file was generated by the Gradle 'init' task.
 */

object Version {
    const val ktor = "1.5.2"
    const val koin = "3.0.1-beta-2"
    const val hapi = "5.2.0"
    const val token_validation = "1.3.3"
    const val junit = "5.7.1"
    const val mock_oauth = "0.3.1"
    const val logback = "1.2.3"
    const val logstash = "6.6"
    const val kafka = "2.7.0"
    const val hoplite = "1.3.0"
}

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("playground.kotlin-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

dependencies {
    implementation("ca.uhn.hapi.fhir:hapi-fhir-structures-r4:${Version.hapi}")
}