/*
 * This file was generated by the Gradle 'init' task.
 */

val hapiVersion = "5.2.0"

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("playground.kotlin-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

dependencies {
    implementation("ca.uhn.hapi.fhir:hapi-fhir-structures-r4:${hapiVersion}")
}