on:
  repository_dispatch:
    types: [build-and-deploy]

jobs:
  main:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "Hello World!"
          echo  "Payload: ${{ github.event.client_payload }}"
