name: build and deploy

on:
  workflow_run:
    workflows: [trigger-build-and-deploy]
    branches: [main]
    types: [completed]

jobs:
  main:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "Hello World!"
          echo  "Context: ${{ github }}"
