on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1.6.0

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2.7.0
        with:
          target: build1
          cache-from: type=gha

      - uses: docker/build-push-action@v2.7.0
        with:
          build-args: project=app
          #push: true
          tags: ghcr.io/eirikmyklebost/playground/test-app:latest
