name: deploy kafka topic

on:
  workflow_dispatch:
    inputs:
      deploy-prod:
        description: 'If the build should also be deployed to production (must be main branch.)'
        required: false
        default: 'false'

jobs:
  deploy:
    name: Deploy kafka
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Deploy to Dev
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka/nais-kafka-topic.yaml
          PRINT_PAYLOAD: true
        run: echo "Deploy to Dev!"

  - name: Deploy to Prod
        if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.deploy-prod == 'true'}}
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka/nais-kafka-topic.yaml
          PRINT_PAYLOAD: true
        run: echo "Deploy to Prod!"
