on: [pull_request]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v1
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          github-token: ${{ secrets.github_token }}
