name: trigger-build-and-deploy

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App name, e.g. hops-api'
        required: true

jobs:
  main:
    name: "Trigger build and deploy of ${{ github.event.inputs.app }}"
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "MY TRIGGER! ${{ github.event.inputs.app }}"
          echo  "Context: ${{ toJSON(github) }}"
